quarkus.management.enabled=true
quarkus.live-reload.password=abc123
#quarkus.kubernetes.env.vars.QUARKUS_LAUNCH_DEVMODE = true
quarkus.kubernetes-config.enabled = true
#quarkus.kubernetes.config-map-volumes.config-volume.config-map-name  = sample-quarkus-k8s
#quarkus.kubernetes.config-map-volumes.config-volume.read-only = true
#quarkus.kubernetes.mounts.config-volume.path=/home/jboss/config
#quarkus.kubernetes.config-map-volumes.config-volume.default-mode = 420
quarkus.container-image.group=fabricio211
quarkus.kubernetes.labels.app=example-quarkus-k8s-ch1
quarkus.kubernetes.prometheus.generate-service-monitor=true
quarkus.kubernetes.prometheus.labels.release=kube-prom-stack
quarkus.kubernetes.namespace=default
quarkus.kubernetes.prometheus.namespace=observability

# porta http principal
quarkus.kubernetes.ports.http.container-port=8080

# porta management/prometheus
quarkus.kubernetes.ports.management.container-port=9000
quarkus.kubernetes.ports.management.name=management

#kubectl label servicemonitor example-quarkus-k8s-ch1 release=kube-prom-stack -n default