quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${POSTGRES_USER}
%prod.quarkus.datasource.password=${POSTGRES_PASSWORD}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://person-db-postgresql:5432/${POSTGRES_DB}
%prod.quarkus.log.console.json.enabled=true


quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.kubernetes-client.namespace=default
quarkus.kubernetes.env.vars.postgres-user=quarkus
quarkus.kubernetes.env.vars.postgres-db=quarkus
quarkus.kubernetes.env.mapping.postgres-password.from-secret=person-db-postgresql
quarkus.kubernetes.env.mapping.postgres-password.with-key=password
quarkus.kubernetes.service-type=NodePort
quarkus.kubernetes.labels.env=dev
quarkus.kubernetes.annotations.app-type=demo

quarkus.package.jar.type=mutable-jar
quarkus.live-reload.password=abc123
quarkus.openshift.env.vars.QUARKUS_LAUNCH_DEVMODE=true